# configire 2 so the 2 virtual machines are created, we need a new do block 
#(the config | DO | block)

Vagrant.configure("2") do |config|

  config.vm.define "app" do |app|
  # configures the VM settings
    app.vm.box = "ubuntu/bionic64"
    app.vm.network "private_network", ip:"192.168.10.100"

  # put the app folder from our local machine
    app.vm.synced_folder"app","/home/vagrant/app"

  # provision the VM to have Nginx
    app.vm.provision "shell", path: "provision .sh"
  end
  
  config.vm.define "db" do |db|
    
    db.vm.box = "ubuntu/bionic64"
    db.vm.network "private_network", ip:"192.168.10.150"  #you can pick any number between 1-250

    db.vm.synced_folder "environment", "/home/vagrant/environment"



  end
end
